### ISSUE TITLE
add S3BucketNotificationConfiguration resource

### ISSUE THREAD

**Issue by kellyoung** [mapbox/magic-cfn-resources#10]
Add the ability to configure a topic to get notifications from an S3 bucket on CloudFormation stack creation, update and delete.

For creation and update:
it will make a call to getNotificationConfiguration to see what configurations are there and putNotificationConfiguration with the new Topic, event, and filters. 

For delete:
the resource will remove the configuration created in the stack.

cc: @rclark @jakepruitt

**Comment by rclark** [comment]
This will be so nice in the future!
